#ifndef __HAIRSIMCOMPUTE_CONFIG__
#define __HAIRSIMCOMPUTE_CONFIG__

#define LAYOUT_INTERLEAVED 1

#define MAX_BOUNDARIES 8

#define DENSITY_SCALE 8192.0
#define DENSITY_TRILINEAR 1

#endif//__HAIRSIMCOMPUTE_CONFIG__
