#ifndef __HAIR_SIM_COMPUTE_CONFIG_HLSL__
#define __HAIR_SIM_COMPUTE_CONFIG_HLSL__

#define LAYOUT_INTERLEAVED 1

#define MAX_BOUNDARIES 8

#define DENSITY_SCALE 8192.0
#define DENSITY_TRILINEAR 1

#endif//__HAIR_SIM_COMPUTE_CONFIG_HLSL__
